# Generated by Django 5.1.7 on 2025-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedproject',
            name='return_period',
            field=models.CharField(choices=[('2m', '2 Minute'), ('10m', '10 Minutes'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual')], max_length=20),
        ),
    ]
