# Generated by Django 5.1.7 on 2025-03-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0004_alter_assignedproject_return_period'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedproject',
            unique_together={('user', 'project')},
        ),
    ]
