# Generated by Django 5.1.7 on 2025-03-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0005_alter_assignedproject_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('project_name', models.CharField(max_length=255)),
                ('narration', models.TextField(blank=True, null=True)),
                ('investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='mafazaapp.transaction')),
            ],
        ),
    ]
