# Generated by Django 5.1.7 on 2025-03-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0006_userledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_calculated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
