# Generated by Django 5.1.7 on 2025-03-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0007_transaction_last_calculated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='last_calculated',
        ),
    ]
