# Generated by Django 5.1.7 on 2025-03-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0010_userledger_created_at_userledger_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userledger',
            old_name='investment',
            new_name='principal_investment',
        ),
    ]
