# Generated by Django 5.1.7 on 2025-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0011_rename_investment_userledger_principal_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userledger',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
