# Generated by Django 5.1.6 on 2025-03-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0015_passwordresetrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
