# Generated by Django 5.1.7 on 2025-03-26 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0017_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoMinuteAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('is_triggered', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafazaapp.investmentproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['due_at', 'is_triggered'], name='mafazaapp_t_due_at_b2f9a9_idx')],
            },
        ),
    ]
