# Generated by Django 5.1.6 on 2025-03-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafazaapp', '0018_twominutealert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoMinuteAlert',
        ),
    ]
